using System;
using System.Collections.Generic;
using System.Linq;

public static class Data
{
    public static Dictionary<string, ModuleInfo> data = new ModuleInfo[]
    {
        new ModuleInfoAll("0", "0"),
        new ModuleInfoAll("3N+1", "threeNPlusOne"),
        new ModuleInfoAll("8", "GSEight"),
        new ModuleInfoAll("A Message", "AMessage"),
        new ModuleInfoAll("ASCII Art", "asciiArt"),
        new ModuleInfoAll("ASCII Maze", "asciiMaze"),
        new ModuleInfoAll("Accelerando", "accelerando"),
        new ModuleInfoAll("Access Codes", "GSAccessCodes"),
        new ModuleInfoAll("Accumulation", "accumulation"),
        new ModuleInfoAll("Addition", "Addition"),
        new ModuleInfoAll("Adjacent Letters", "AdjacentLettersModule"),
        new ModuleInfoAll("Adventure Game", "spwizAdventureGame"),
        new ModuleInfoAll("Affine Cycle", "affineCycle"),
        new ModuleInfoAll("Alchemy", "JuckAlchemy"),
        new ModuleInfoAll("Alfa-Bravo", "alfa_bravo"),
        new ModuleInfoAll("Algebra", "algebra"),
        new ModuleInfoAll("Answering Can Be Fun", "AnsweringCanBeFun"),
        new ModuleInfoAll("Antichamber", "antichamber"),
        new ModuleInfoAll("Arithmetic Cipher", "ArithmeticCipherModule"),
        new ModuleInfoAll("Ars Goetia Identification", "arsGoetiaIdentification"),
        new ModuleInfoAll("Atbash Cipher", "AtbashCipher"),
        new ModuleInfoAll("Audio Morse", "lgndAudioMorse"),
        new ModuleInfoAll("Backdoor Hacking", "BackdoorHacking"),
        new ModuleInfoAll("Backgrounds", "Backgrounds"),
        new ModuleInfoAll("Bartending", "BartendingModule"),
        new ModuleInfoAll("Base-1", "base1"),
        new ModuleInfoAll("Basic Morse", "BasicMorse"),
        new ModuleInfoAll("Benedict Cumberbatch", "benedictCumberbatch"),
        new ModuleInfoAll("Binary Buttons", "BinaryButtons"),
        new ModuleInfoAll("Binary Cipher", "binarycipher"),
        new ModuleInfoAll("Binary Grid", "binaryGrid"),
        new ModuleInfoAll("Binary Morse", "binaryMorse"),
        new ModuleInfoAll("Binary", "Binary"),
        new ModuleInfoAll("Bitmaps", "BitmapsModule"),
        new ModuleInfoAll("Bitwise Operations", "BitOps"),
        new ModuleInfoAll("Blackjack", "KritBlackjack"),
        new ModuleInfoAll("Blank Card", "blankCard"),
        new ModuleInfoAll("Blaseball", "krazzBlaseball"),
        new ModuleInfoAll("Blind Maze", "BlindMaze"),
        new ModuleInfoAll("Blockbusters", "blockbusters"),
        new ModuleInfoAll("Blue Cipher", "blueCipher"),
        new ModuleInfoAll("Blue Huffman Cipher", "BlueHuffmanCipherModule"),
        new ModuleInfoAll("Bomb It!", "BombItModule"),
        new ModuleInfoAll("Bone Apple Tea", "boneAppleTea"),
        new ModuleInfoAll("Boolean Maze", "boolMaze"),
        new ModuleInfoAll("Boomdas", "boomdas"),
        new ModuleInfoAll("Boozlesnap", "boozlesnap"),
        new ModuleInfoAll("Bowling", "Bowling"),
        new ModuleInfoAll("Boxing", "boxing"),
        new ModuleInfoAll("Brainf---", "brainf"),
        new ModuleInfoAll("Breaktime", "breaktime"),
        new ModuleInfoAll("Bridge", "bridge"),
        new ModuleInfoAll("Broken Buttons", "BrokenButtonsModule"),
        new ModuleInfoAll("Brown Cipher", "brownCipher"),
        new ModuleInfoAll("Button Order", "buttonOrder"),
        new ModuleInfoAll("CA-RPS", "caRPS"),
        new ModuleInfoAll("Caesar Cycle", "caesarCycle"),
        new ModuleInfoAll("Calculus", "calcModule"),
        new ModuleInfoAll("Castor", "CastorModule"),
        new ModuleInfoAll("Catchphrase", "catchphrase"),
        new ModuleInfoAll("Challenge & Contact", "challengeAndContact"),
        new ModuleInfoAll("Chaotic Countdown", "ChaoticCountdownModule"),
        new ModuleInfoAll("Character Slots", "characterSlots"),
        new ModuleInfoAll("Cheap Checkout", "CheapCheckoutModule"),
        new ModuleInfoAll("Cheep Checkout", "cheepCheckout"),
        new ModuleInfoAll("Chessword", "ChesswordModule"),
        new ModuleInfoAll("Chinese Strokes", "zhStrokes"),
        new ModuleInfoAll("Chinese Zodiac", "xelChineseZodiac"),
        new ModuleInfoAll("Chord Progressions", "chordProgressions"),
        new ModuleInfoAll("Cipher Machine", "cipherMachine"),
        new ModuleInfoAll("Cistercian Numbers", "xelCistercianNumbers"),
        new ModuleInfoAll("Coffeebucks", "coffeebucks"),
        new ModuleInfoAll("Colo(u)r Talk", "colourTalk"),
        new ModuleInfoAll("Color Math", "colormath"),
        new ModuleInfoAll("Color One Two", "colorOneTwo"),
        new ModuleInfoAll("Color-Cycle Button", "colorCycleButton"),
        new ModuleInfoAll("Colorful Dials", "colorfulDials"),
        new ModuleInfoAll("Colors Maximization", "colors_maximization"),
        new ModuleInfoAll("Colour Code", "colourcode"),
        new ModuleInfoAll("Combination Lock", "combinationLock"),
        new ModuleInfoAll("Connection Check", "graphModule"),
        new ModuleInfoAll("Cooking", "cooking"),
        new ModuleInfoAll("Cornflower Cipher", "cornflowerCipher"),
        new ModuleInfoAll("Cosmic", "CosmicModule"),
        new ModuleInfoAll("Crimson Cipher", "crimsonCipher"),
        new ModuleInfoAll("Critters", "CrittersModule"),
        new ModuleInfoAll("Cruel Binary", "CruelBinary"),
        new ModuleInfoAll("Cruel Boolean Maze", "boolMazeCruel"),
        new ModuleInfoAll("Cruel Colour Flash", "cruelColourFlash"),
        new ModuleInfoAll("Cruel Modulo", "cruelModulo"),
        new ModuleInfoAll("Cryptic Password", "CrypticPassword"),
        new ModuleInfoAll("Crypto Market", "cryptoMarket"),
        new ModuleInfoAll("Currents", "Currents"),
        new ModuleInfoAll("Curriculum", "curriculum"),
        new ModuleInfoAll("Customer Identification", "xelCustomerIdentification"),
        new ModuleInfoAll("Daylight Directions", "daylightDirections"),
        new ModuleInfoAll("Deck Creating", "kataDeckCreating"),
        new ModuleInfoAll("Dice Cipher", "diceCipher"),
        new ModuleInfoAll("Dictation", "Dictation"),
        new ModuleInfoAll("Digital Dials", "digitalDials"),
        new ModuleInfoAll("Digital Grid", "digitalGrid"),
        new ModuleInfoAll("Discolour Flash", "discolourFlash"),
        new ModuleInfoAll("Divisible Numbers", "divisibleNumbers"),
        new ModuleInfoAll("Dominoes", "dominoes"),
        new ModuleInfoAll("Don't Touch Anything", "dontTouchAnything"),
        new ModuleInfoAll("Double Color", "doubleColor"),
        new ModuleInfoAll("Double Digits", "doubleDigitsModule"),
        new ModuleInfoAll("Double Expert", "doubleExpert"),
        new ModuleInfoAll("Double Pitch", "DoublePitch"),
        new ModuleInfoAll("Dragon Energy", "dragonEnergy"),
        new ModuleInfoAll("Dual Sequences", "dualSequences"),
        new ModuleInfoAll("Dumb Waiters", "dumbWaiters"),
        new ModuleInfoAll("Eight", "eight"),
        new ModuleInfoAll("Emotiguy Identification", "EmotiguyIdentification"),
        new ModuleInfoAll("Encrypted Dice", "EncryptedDice"),
        new ModuleInfoAll("Encrypted Equations", "EncryptedEquationsModule"),
        new ModuleInfoAll("Encrypted Morse", "EncryptedMorse"),
        new ModuleInfoAll("Encryption Lingo", "EncryptionLingoModule"),
        new ModuleInfoAll("English Entries", "EnglishEntries"),
        new ModuleInfoAll("Equations X", "equationsXModule"),
        new ModuleInfoAll("Error Codes", "errorCodes"),
        new ModuleInfoAll("Face Recognition", "xelFaceRecognition"),
        new ModuleInfoAll("Factory Code", "factoryCode"),
        new ModuleInfoAll("Fast Math", "fastMath"),
        new ModuleInfoAll("Faulty 14 Segment Display", "Faulty14SegmentDisplayModule"),
        new ModuleInfoAll("Faulty Accelerando", "faultyAccelerandoModule"),
        new ModuleInfoAll("Faulty Binary", "FaultyBinary"),
        new ModuleInfoAll("Faulty Digital Root", "faultyDigitalRootModule"),
        new ModuleInfoAll("Feature Cryptography", "featureCryptography"),
        new ModuleInfoAll("Fishing", "fishing"),
        new ModuleInfoAll("Fitting In", "FittingInModule"),
        new ModuleInfoAll("FizzBuzz", "fizzBuzzModule"),
        new ModuleInfoAll("Flags", "FlagsModule"),
        new ModuleInfoAll("Flavor Text", "FlavorText"),
        new ModuleInfoAll("Forest Cipher", "forestCipher"),
        new ModuleInfoAll("Forget Enigma", "forgetEnigma"),
        new ModuleInfoAll("Four-Card Monte", "Krit4CardMonte"),
        new ModuleInfoAll("Fruits", "fruits"),
        new ModuleInfoAll("Functions", "qFunctions"),
        new ModuleInfoAll("Game of Life Cruel", "GameOfLifeCruel"),
        new ModuleInfoAll("Game of Life Simple", "GameOfLifeSimple"),
        new ModuleInfoAll("Generated Maze", "genMaze"),
        new ModuleInfoAll("Genetic Sequence", "geneticSequence"),
        new ModuleInfoAll("Geometry Dash", "geometryDashModule"),
        new ModuleInfoAll("Geometry", "Geometry"),
        new ModuleInfoAll("Golf", "golf"),
        new ModuleInfoAll("Gray Cipher", "grayCipher"),
        new ModuleInfoAll("Greek Calculus", "greekCalculus"),
        new ModuleInfoAll("Greek Letter Grid", "greekLetterGrid"),
        new ModuleInfoAll("Green Cipher", "greenCipher"),
        new ModuleInfoAll("Grid Matching", "GridMatching"),
        new ModuleInfoAll("Gridlock", "GridlockModule"),
        new ModuleInfoAll("Grocery Store", "groceryStore"),
        new ModuleInfoAll("Hand Turkey", "handTurkey"),
        new ModuleInfoAll("Hereditary Base Notation", "hereditaryBaseNotationModule"),
        new ModuleInfoAll("Hertz", "hertz"),
        new ModuleInfoAll("Hill Cycle", "hillCycle"),
        new ModuleInfoAll("Hold On", "ashHoldOn"),
        new ModuleInfoAll("Homophones", "homophones"),
        new ModuleInfoAll("Human Resources", "HumanResourcesModule"),
        new ModuleInfoAll("I'm Not a Robot", "CaptchaModule"),
        new ModuleInfoAll("Ice Cream", "iceCreamModule"),
        new ModuleInfoAll("Icon Reveal", "IconReveal"),
        new ModuleInfoAll("Identification Crisis", "identificationCrisis"),
        new ModuleInfoAll("Identifying Soulless", "identifyingSoulless"),
        new ModuleInfoAll("Identity Parade", "identityParade"),
        new ModuleInfoAll("Increasing Indices", "increasingIndices"),
        new ModuleInfoAll("Indigo Cipher", "indigoCipher"),
        new ModuleInfoAll("Ingredients", "ingredients"),
        new ModuleInfoAll("Insanagrams", "insanagrams"),
        new ModuleInfoAll("Inside", "SCP2719"),
        new ModuleInfoAll("Iron Lung", "ironLung"),
        new ModuleInfoAll("Jackbox.TV", "jackboxServerModule"),
        new ModuleInfoAll("Johnson Solids", "xelJohnsonSolids"),
        new ModuleInfoAll("Jumble Cycle", "jumbleCycle"),
        new ModuleInfoAll("Kahoot!", "Kahoot"),
        new ModuleInfoAll("Keep Clicking", "keepClicking"),
        new ModuleInfoAll("Keypad Maze", "KeypadMaze"),
        new ModuleInfoAll("Kyudoku", "kyudoku"),
        new ModuleInfoAll("LED Math", "lgndLEDMath"),
        new ModuleInfoAll("LEGOs", "LEGOModule"),
        new ModuleInfoAll("LOOK AT ME", "LOOKATME"),
        new ModuleInfoAll("Latin Hypercube", "latinHypercube"),
        new ModuleInfoAll("Lempel-Ziv Cipher", "LempelZivCipherModule"),
        new ModuleInfoAll("Levenshtein Distance", "levenshteinDistance"),
        new ModuleInfoAll("Life Iteration", "LifeIteration"),
        new ModuleInfoAll("Line Equations", "GSLineEquations"),
        new ModuleInfoAll("Lines of Code", "linesOfCode"),
        new ModuleInfoAll("Logic", "Logic"),
        new ModuleInfoAll("Lunchtime", "lunchtime"),
        new ModuleInfoAll("Mahjong Quiz Easy", "MahjongQuizEasy"),
        new ModuleInfoAll("Mahjong Quiz Hard", "MahjongQuizHard"),
        new ModuleInfoAll("Mahjong Quiz Scrambled", "MahjongQuizScrambled"),
        new ModuleInfoAll("Maintenance", "maintenance"),
        new ModuleInfoAll("Malfunctions", "malfunctions"),
        new ModuleInfoAll("Maroon Cipher", "maroonCipher"),
        new ModuleInfoAll("Mashematics", "mashematics"),
        new ModuleInfoAll("Masked Morse", "maskedMorse"),
        new ModuleInfoAll("Mastermind Cruel", "Mastermind Cruel"),
        new ModuleInfoAll("Mastermind Restricted Cruel", "mastermindRestrictedCruel"),
        new ModuleInfoAll("Mastermind Simple", "Mastermind Simple"),
        new ModuleInfoAll("Matchematics", "matchematics"),
        new ModuleInfoAll("Matchmaker", "matchmaker"),
        new ModuleInfoAll("Math 'em", "mathem"),
        new ModuleInfoAll("Maze Identification", "GSMazeIdentification"),
        new ModuleInfoAll("Maze Scrambler", "MazeScrambler"),
        new ModuleInfoAll("Mega Man 2", "megaMan2"),
        new ModuleInfoAll("Melody Memory", "melodyMemory"),
        new ModuleInfoAll("Meme Review", "memeReviewModule"),
        new ModuleInfoAll("Meteor", "meteor"),
        new ModuleInfoAll("Meter", "meter"),
        new ModuleInfoAll("Micro-Modules", "KritMicroModules"),
        new ModuleInfoAll("Mineseeker", "mineseeker"),
        new ModuleInfoAll("Minesweeper", "MinesweeperModule"),
        new ModuleInfoAll("Mischboozl", "Mischboozl"),
        new ModuleInfoAll("Modern Cipher", "modernCipher"),
        new ModuleInfoAll("Modules Against Humanity", "ModuleAgainstHumanity"),
        new ModuleInfoAll("Modulo", "modulo"),
        new ModuleInfoAll("Modulus Manipulation", "modulusManipulation"),
        new ModuleInfoAll("Monsplode Trading Cards", "monsplodeCards"),
        new ModuleInfoAll("Morse War", "MorseWar"),
        new ModuleInfoAll("Moved", "simpleMove"),
        new ModuleInfoAll("Mssngv Wls", "MssngvWls"),
        new ModuleInfoAll("Murder", "murder"),
        new ModuleInfoAll("Musical Transposition", "MusicalTransposition"),
        new ModuleInfoAll("My Mom", "myMom"),
        new ModuleInfoAll("Natures", "mcdNatures"),
        new ModuleInfoAll("Negativity", "Negativity"),
        new ModuleInfoAll("Neutralization", "neutralization"),
        new ModuleInfoAll("Newline", "newline"),
        new ModuleInfoAll("Nifty Number", "NiftyNumber"),
        new ModuleInfoAll("Nonbinary Puzzle", "nonbinaryPuzzle"),
        new ModuleInfoAll("Nonogram", "NonogramModule"),
        new ModuleInfoAll("Not Bitmaps", "NotBitmapsModule"),
        new ModuleInfoAll("Not Connection Check", "notConnectionCheck"),
        new ModuleInfoAll("Not Identification", "notIdentification"),
        new ModuleInfoAll("Not Murder", "notMurder"),
        new ModuleInfoAll("Not Number Pad", "notNumberPad"),
        new ModuleInfoAll("Not Poker", "NotPokerModule"),
        new ModuleInfoAll("Not Symbolic Coordinates", "notSymbolicCoordinates"),
        new ModuleInfoAll("Not Symbolic Password", "NotSymbolicPasswordModule"),
        new ModuleInfoAll("Notes", "notes"),
        new ModuleInfoAll("Notre-Dame Cipher", "notreDameCipher"),
        new ModuleInfoAll("Number Sequence", "numberSequence"),
        new ModuleInfoAll("Numbers", "Numbers"),
        new ModuleInfoAll("One Links To All", "oneLinksToAllModule"),
        new ModuleInfoAll("Orange Cipher", "orangeCipher"),
        new ModuleInfoAll("Outrageous", "outrageous"),
        new ModuleInfoAll("Over Kilo", "overKilo"),
        new ModuleInfoAll("Palindromes", "palindromes"),
        new ModuleInfoAll("Pandemonium Cipher", "pandemoniumCipher"),
        new ModuleInfoAll("Papa's Pizzeria", "papasPizzeria"),
        new ModuleInfoAll("Parliament", "parliament"),
        new ModuleInfoAll("Partial Derivatives", "partialDerivatives"),
        new ModuleInfoAll("Password Destroyer", "pwDestroyer"),
        new ModuleInfoAll("Pawns", "pawns"),
        new ModuleInfoAll("Pickup Identification", "PickupIdentification"),
        new ModuleInfoAll("Pigpen Cycle", "pigpenCycle"),
        new ModuleInfoAll("Pigpen Rotations", "pigpenRotations"),
        new ModuleInfoAll("Pixel Number Base", "PixelNumberBase"),
        new ModuleInfoAll("Placement Roulette", "PlacementRouletteModule"),
        new ModuleInfoAll("Planets", "planets"),
        new ModuleInfoAll("Plant Identification", "PlantIdentification"),
        new ModuleInfoAll("Playfair Cycle", "playfairCycle"),
        new ModuleInfoAll("Plumbing", "MazeV2"),
        new ModuleInfoAll("Poker", "Poker"),
        new ModuleInfoAll("Pokémon Sprite Cipher", "PokemonSpriteCipherModule"),
        new ModuleInfoAll("Pollux", "PolluxModule"),
        new ModuleInfoAll("Purchasing Properties", "PurchasingProperties"),
        new ModuleInfoAll("Puzzle Identification", "GSPuzzleIdentification"),
        new ModuleInfoAll("Quaternions", "quaternions"),
        new ModuleInfoAll("Quaver", "Quaver"),
        new ModuleInfoAll("Quintuples", "quintuples"),
        new ModuleInfoAll("Quiz Buzz", "quizBuzz"),
        new ModuleInfoAll("Quote Crazy Talk End Quote", "QuoteCrazyTalkEndQuote"),
        new ModuleInfoAll("RGB Quiz", "RGBQuiz"),
        new ModuleInfoAll("Radiator", "radiator"),
        new ModuleInfoAll("Rain Hell", "rainHellModule"),
        new ModuleInfoAll("Rain", "rainModule"),
        new ModuleInfoAll("ReGret-B Filtering", "regretbFiltering"),
        new ModuleInfoAll("ReGrettaBle Relay", "regrettablerelay"),
        new ModuleInfoAll("Reading Between the Lines", "ReadingBetweentheLines"),
        new ModuleInfoAll("Red Cipher", "redCipher"),
        new ModuleInfoAll("Reformed Role Reversal", "ReformedRoleReversal"),
        new ModuleInfoAll("Regular Hexpressions", "RegularHexpressions"),
        new ModuleInfoAll("Resistors", "resistors"),
        new ModuleInfoAll("Retirement", "retirement"),
        new ModuleInfoAll("Reverse Morse", "reverseMorse"),
        new ModuleInfoAll("Reverse Polish Notation", "revPolNot"),
        new ModuleInfoAll("Risky Wires", "riskyWires"),
        new ModuleInfoAll("Robit Programming", "robitProgramming"),
        new ModuleInfoAll("Robot Programming", "robotProgramming"),
        new ModuleInfoAll("Roguelike Game", "roguelikeGame"),
        new ModuleInfoAll("Role Reversal", "roleReversal"),
        new ModuleInfoAll("Rubik’s Clock", "rubiksClock"),
        new ModuleInfoAll("SI-HTS", "SIHTS"),
        new ModuleInfoAll("SQL - Basic", "sqlBasic"),
        new ModuleInfoAll("SQL - Cruel", "sqlCruel"),
        new ModuleInfoAll("SQL - Evil", "sqlEvil"),
        new ModuleInfoAll("Scalar Dials", "scalarDials"),
        new ModuleInfoAll("Schlag den Bomb", "qSchlagDenBomb"),
        new ModuleInfoAll("Scrabble Scramble", "scrabbleScramble"),
        new ModuleInfoAll("Scratch-Off", "scratchOff"),
        new ModuleInfoAll("Scripting", "KritScripts"),
        new ModuleInfoAll("Sequences", "sequencesModule"),
        new ModuleInfoAll("Shape Cipher", "shapeCipher"),
        new ModuleInfoAll("Shapes And Bombs", "ShapesBombs"),
        new ModuleInfoAll("Shell Game", "shellGame"),
        new ModuleInfoAll("Shifting Maze", "MazeShifting"),
        new ModuleInfoAll("Shufflewords", "shufflewords"),
        new ModuleInfoAll("Shut-the-Box", "ShutTheBox"),
        new ModuleInfoAll("Silly Slots", "SillySlots"),
        new ModuleInfoAll("Silo Authorization", "siloAuthorization"),
        new ModuleInfoAll("Simon Selects", "simonSelectsModule"),
        new ModuleInfoAll("Simpleton't", "notsimple"),
        new ModuleInfoAll("Sink", "Sink"),
        new ModuleInfoAll("Skewed Slots", "SkewedSlotsModule"),
        new ModuleInfoAll("Skyrim", "skyrim"),
        new ModuleInfoAll("Snack Attack", "SnackAttack"),
        new ModuleInfoAll("Sonic the Hedgehog", "sonic"),
        new ModuleInfoAll("Sorry Sliders", "SorrySliders"),
        new ModuleInfoAll("Spilling Paint", "spillingPaint"),
        new ModuleInfoAll("SpriteClub Betting Simulation", "SpriteClubBettingSimulation"),
        new ModuleInfoAll("Standard Button Masher", "standardButtonMasher"),
        new ModuleInfoAll("Starmap Reconstruction", "starmap_reconstruction"),
        new ModuleInfoAll("State of Aggregation", "stateOfAggregation"),
        new ModuleInfoAll("Subscribe to Pewdiepie", "subscribeToPewdiepie"),
        new ModuleInfoAll("Subways", "subways"),
        new ModuleInfoAll("Switching Maze", "MazeSwitching"),
        new ModuleInfoAll("Symbolic Coordinates", "symbolicCoordinates"),
        new ModuleInfoAll("Symbolic Password", "symbolicPasswordModule"),
        new ModuleInfoAll("Taco Tuesday", "tacoTuesday"),
        new ModuleInfoAll("Ternary Converter", "qkTernaryConverter"),
        new ModuleInfoAll("Ternary Tiles", "GSTernaryTiles"),
        new ModuleInfoAll("Tesseractivity", "Tesseractivity"),
        new ModuleInfoAll("TetraVex", "ksmTetraVex"),
        new ModuleInfoAll("Tetramorse", "Tetramorse"),
        new ModuleInfoAll("The Amber Button", "AmberButtonModule"),
        new ModuleInfoAll("The Black Button", "BlackButtonModule"),
        new ModuleInfoAll("The Black Page", "TheBlackPage"),
        new ModuleInfoAll("The Calculator", "TheCalculator"),
        new ModuleInfoAll("The Code", "theCodeModule"),
        new ModuleInfoAll("The Colored Maze", "coloredMaze"),
        new ModuleInfoAll("The Dealmaker", "thedealmaker"),
        new ModuleInfoAll("The Deck of Many Things", "deckOfManyThings"),
        new ModuleInfoAll("The Door", "FlipDoor"),
        new ModuleInfoAll("The Exploding Pen", "TheExplodingPen"),
        new ModuleInfoAll("The Festive Jukebox", "festiveJukebox"),
        new ModuleInfoAll("The Funny Number", "funnyNumber"),
        new ModuleInfoAll("The Furloid Jukebox", "xelFurloidJukebox"),
        new ModuleInfoAll("The Jukebox", "jukebox"),
        new ModuleInfoAll("The Logan Parody Jukebox", "LoganJukebox"),
        new ModuleInfoAll("The Modkit", "modkit"),
        new ModuleInfoAll("The Number Cipher", "numberCipher"),
        new ModuleInfoAll("The Number", "theNumber"),
        new ModuleInfoAll("The Rule", "theRule"),
        new ModuleInfoAll("The Stock Market", "stockMarket"),
        new ModuleInfoAll("The Swan", "theSwan"),
        new ModuleInfoAll("The Tile Maze", "theTileMazeModule"),
        new ModuleInfoAll("The cRule", "the_cRule"),
        new ModuleInfoAll("Timezone", "timezone"),
        new ModuleInfoAll("Timing is Everything", "timingIsEverything"),
        new ModuleInfoAll("Toon Enough", "toonEnough"),
        new ModuleInfoAll("Top 10 Numbers", "top10nums"),
        new ModuleInfoAll("Topsy Turvy", "topsyTurvy"),
        new ModuleInfoAll("Totally Accurate Minecraft Simulator", "tams"),
        new ModuleInfoAll("Touch Transmission", "touchTransmission"),
        new ModuleInfoAll("Towers", "Towers"),
        new ModuleInfoAll("Training Text", "TrainingText"),
        new ModuleInfoAll("Transmitted Morse", "transmittedMorseModule"),
        new ModuleInfoAll("Tribal Council", "TribalCouncil"),
        new ModuleInfoAll("Triple Term", "tripleTermModule"),
        new ModuleInfoAll("Truchet Tiles", "xelTruchetTiles"),
        new ModuleInfoAll("Turtle Robot", "turtleRobot"),
        new ModuleInfoAll("Two Bits", "TwoBits"),
        new ModuleInfoAll("UIN(+L)", "UINpL"),
        new ModuleInfoAll("Ultimate Cycle", "ultimateCycle"),
        new ModuleInfoAll("Ultralogic", "Ultralogic"),
        new ModuleInfoAll("Unicode", "UnicodeModule"),
        new ModuleInfoAll("Unown Cipher", "UnownCipher"),
        new ModuleInfoAll("Violet Cipher", "violetCipher"),
        new ModuleInfoAll("Wack Game of Life", "wackGameOfLife"),
        new ModuleInfoAll("Weird Al Yankovic", "weirdAlYankovic"),
        new ModuleInfoAll("Wendithap'n", "Wendithapn"),
        new ModuleInfoAll("White Cipher", "whiteCipher"),
        new ModuleInfoAll("Wolf, Goat, and Cabbage", "wolfGoatCabbageModule"),
        new ModuleInfoAll("Wonder Cipher", "WonderCipher"),
        new ModuleInfoAll("Yellow Cipher", "yellowCipher"),
        new ModuleInfoAll("Yellow Huffman Cipher", "YellowHuffmanCipherModule"),
        new ModuleInfoAll("eeB gnillepS", "eeBgnilleps"),
        new ModuleInfoAll("Ángel Hernández", "AngelHernandezModule"),
        new ModuleInfoAll("ƎNA Cipher", "enaCipher"),

        //Unused =
        //new ModuleInfoAll("1000 Words", "OneThousandWords"),
        //new ModuleInfoAll("14", "14"),
        //new ModuleInfoAll("Amnesia", "Amnesia"),
        //new ModuleInfoAll("Antistress", "antistress"),
        //new ModuleInfoAll("Broken Guitar Chords", "BrokenGuitarChordsModule"),
        //new ModuleInfoAll("Burnout", "kataBurnout"),
        //new ModuleInfoAll("Dialtones", "xelDialtones"),
        //new ModuleInfoAll("DNA Mutation", "DNAMutation"),
        //new ModuleInfoAll("Enigma Cycle", "enigmaCycle"),
        //new ModuleInfoAll("Finite Loop", "finiteLoop"),
        //new ModuleInfoAll("Functional Mapping", "functionalMapping"),
    }
    .ToDictionary(x => x.displayName);
}